Repository NVIDIA/earth2mip, pull requests merged in 2023-10, with the labels that each got.

#55 Enh: Adding model package download functions to loads
  earth2mip/model_registry.py
  earth2mip/networks/__init__.py
  earth2mip/networks/dlwp.py
  earth2mip/networks/fcnv2_sm.py
  earth2mip/networks/pangu.py
  examples/README.md
  examples/configs/ensemble_pangu24_cds.json
  examples/workflows/dlwp.py
  examples/workflows/fcnv2_sm.py
  examples/workflows/pangu_24.py
  setup.cfg
Labels: enhancement, 3 - Ready for Review

#36 Adding FCN
  README.md
  earth2mip/inference_ensemble.py
  earth2mip/initial_conditions/__init__.py
  earth2mip/model_registry.py
  earth2mip/networks/dlwp.py
  earth2mip/networks/fcn.py
  earth2mip/regrid.py
  earth2mip/schema.py
  examples/notebooks/02_model_comparison.ipynb
  examples/workflows/fcn.py
  setup.cfg
  tests/test_regrid.py
Labels: 3 - Ready for Review

#60 move normalize and denormalize into perturb
  earth2mip/_channel_stds.py
  earth2mip/inference_ensemble.py
  tests/test_end_to_end.py
Labels: 4 - In Review

#48 Config control on the variables to perturb
  earth2mip/inference_ensemble.py
  earth2mip/schema.py
Labels: 4 - In Review

#73 fix typos
  README.md
  docs/clis.rst
  docs/concepts.rst
  docs/plugin.rst
Labels: 4 - In Review

#85 Adding Diagnostic Model Integration
  CONTRIBUTING.md
  earth2mip/_config.py
  earth2mip/diagnostic/__init__.py
  earth2mip/diagnostic/base.py
  earth2mip/diagnostic/climate_net.py
  earth2mip/diagnostic/precipitation_afno.py
  earth2mip/diagnostic/time_loop.py
  earth2mip/diagnostic/utils.py
  earth2mip/diagnostic/wind_speed.py
  earth2mip/geo_operator.py
  earth2mip/netcdf.py
  earth2mip/networks/__init__.py
  examples/README.md
  examples/workflows/fcn.py
  examples/workflows/fcnv2_sm.py
  examples/workflows/inference_diagnostic_basic.py
  examples/workflows/pangu_24.py
  examples/workflows/run_ensemble_model_noise.py
  requirements.txt
  tests/diagnostics/test_climatenet.py
  tests/diagnostics/test_diagnostic_loop.py
  tests/diagnostics/test_precipitation.py
  tests/diagnostics/test_utils.py
  tests/diagnostics/test_windspeed.py
Labels: 4 - In Review
