Repository NVIDIA/earth2mip, pull requests merged in 2023-09, with the labels that each got.

#4 Apptainer build + notebook improvements
  .gitignore
  examples/README.md
  examples/earth2mip.def
  examples/notebooks/01_ensemble_inference.ipynb
  examples/notebooks/02_model_comparison.ipynb
Labels: enhancement

#6 sort ensemble files before opening them in score_ensemble_outputs
  CHANGELOG.md
  earth2mip/score_ensemble_outputs.py
Labels: bug, external

#10 README update
  README.md
Labels: documentation

#20 fix: Readme update and fixes
  README.md
Labels: documentation

#21 fix: update templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_request.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/worksflows/blossom-ci.yml
Labels: documentation, cleanup

#24 fix: Update deps to include CDS libs
  CHANGELOG.md
  examples/notebooks/01_ensemble_inference.ipynb
  examples/notebooks/02_model_comparison.ipynb
  setup.cfg
Labels: bug, enhancement

#25 fix: fixing workflow scripts
  earth2mip/networks/pangu.py
  examples/workflows/dlwp.py
  examples/workflows/fcnv2_sm.py
  examples/workflows/pangu_24.py
Labels: bug

#30 Update setup.cfg with Pydantic range
  setup.cfg
Labels: bug

#31 Fixing colormap in notebook 1
  examples/notebooks/01_ensemble_inference.ipynb
Labels: bug, 2 - In Progress

#32 Improving Examples Singularity Doc and Conda Env
  examples/README.md
  examples/earth2mip.def
Labels: documentation

#46 Fix: Remove CLI command from Notebook 1 and instead rely on Python API
  examples/notebooks/01_ensemble_inference.ipynb
Labels: 2 - In Progress

#43 add back GRF based ensmeble ic method
  earth2mip/ensemble_utils.py
  earth2mip/inference_ensemble.py
  earth2mip/schema.py
Labels: 4 - In Review
